---
DESIGN_NAME: afifo
VERILOG_FILES: dir::rtl/*.sv
CLOCK_PORT:
  - wclk
  - rclk

PNR_SDC_FILE: constraints.sdc
SIGNOFF_SDC_FILE: constraints.sdc

# Power Distribution Stuff
FP_PDN_VOFFSET: 7
FP_PDN_HOFFSET: 7
FP_PDN_SKIPTRIM: true
RUN_POST_GRT_RESIZER_TIMING: true
RUN_POST_GRT_DESIGN_REPAIR: true
SYNTH_AUTONAME: true
